orbs:
  react: thefrontside/react@0.2.0
  cypress: cypress-io/cypress@1.26.0
version: 2.1

workflows:
  push:
    jobs:
      - react/install
      - react/test:
          requires:
            - react/install
      - cypress/run:
          yarn: true
          start: yarn start
          wait-on: "http://localhost:3000"
